# Generated by Django 5.2 on 2025-04-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='agent_profile/'),
        ),
    ]
