# Generated by Django 5.2 on 2025-04-19 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_agent_age_agent_country_agent_gender_agent_pin_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('profession', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adhar_card', models.CharField(max_length=12)),
                ('pan_card', models.CharField(max_length=10)),
                ('has_kids', models.BooleanField()),
                ('source_of_information', models.CharField(max_length=200)),
                ('customer_service_satisfaction', models.TextField()),
                ('claim_satisfaction', models.TextField()),
                ('insurance_markup_area', models.CharField(max_length=200)),
                ('agent_visited_policy', models.CharField(max_length=200)),
                ('willingness_to_purchase', models.BooleanField()),
                ('customer_preferences', models.TextField()),
                ('willingness_to_switch', models.BooleanField()),
                ('existing_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('existing_insurance_name', models.CharField(blank=True, max_length=100, null=True)),
                ('existing_claim_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
