# Generated by Django 5.2 on 2025-04-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_alter_campaign_agent_alter_clients_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
