# Generated by Django 5.2 on 2025-04-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_clientcampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='end_date',
        ),
    ]
